version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: 'campus_imaotai'
    volumes:
      - /home/shiwenbin/campus-imaotai/doc/docker/mysql/data/:/var/lib/mysql/
      - /home/shiwenbin/campus-imaotai/doc/docker/mysql/conf/:/etc/mysql/conf.d/
      - /home/shiwenbin/campus-imaotai/doc/docker/mysql/logs:/logs
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=80M',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    privileged: true
    network_mode: "host"

  redis:
    image: redis:6.2.12
    container_name: redis
    volumes:
      - /home/shiwenbin/campus-imaotai/doc/docker/redis/conf:/redis/config
      - /home/shiwenbin/campus-imaotai/doc/docker/redis/data/:/redis/data/
    command: "redis-server /redis/config/redis.conf"
    privileged: true
    network_mode: "host"

  nginx-web:
    image: nginx:1.23.4
    container_name: nginx-web
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /home/shiwenbin/campus-imaotai/doc/docker/nginx/html:/usr/share/nginx/html
      - /home/shiwenbin/campus-imaotai/doc/docker/nginx/cert:/etc/nginx/cert
      - /home/shiwenbin/campus-imaotai/doc/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /home/shiwenbin/campus-imaotai/doc/docker/nginx/log:/var/log/nginx
    privileged: true
    network_mode: "host"



#  campus-server:
#    image: campus/campus-imaotai:1.0.11
#    container_name: campus-imaotai
#    environment:
#      # 时区上海
#      TZ: Asia/Shanghai
#      SERVER_PORT: 8160
#      spring.config.additional-location: /home/campus/conf/application-prod.yml
#    volumes:
#      - /docker/server/conf:/home/campus/conf
#    privileged: true
#    network_mode: "host"
